repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.4.0"
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude_types: [json, binary]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.12.0
    hooks:
      # Run the linter.
      - id: ruff-check
        args: [ --fix, --exit-non-zero-on-fix]
      # Run the formatter.
      - id: ruff-format
